### ISSUE TITLE
Small Issue: Downside for Medic

### ISSUE THREAD

**Issue by LukasRainbow** [Siko91/tf2-weapon-generator#9]
There is a Downside for the Medic which is not quite right... Either a Word is missing or something went wrong.

The Downside says: "Drains HP from teammates near to the Medi Gun target **for 8% of the target**, if health of these teammates is more than 50"

I've Highlighted the Issue here. It said it drains HP but doesn't really say the Condition. The Teammates HP gets drained if they're above 50 Health AND if the Healing Target has 8% of something that isn't said.
It's not that big of a Deal but knowing what it means would be quite Nice :)

**Comment by Siko91** [comment]
thanks.

Honestly, I don't remember what that downside was supposed to be.
I'll just go change it to something meaningfull.

**Comment by Siko91** [comment]
Done.
You can see the change here:
https://github.com/Siko91/tf2-weapon-generator/commit/1af12c3640ad1ea2c3517a3a91bb301b7784b2c0
